environment:
  nodejs_version: "12"
#cache:
#  - node_modules
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  - yarn
test_script:
  - node --version
  - npm --version
  - yarn test
build: off